"""Covariate extraction: GEE source registry, dedup, chunk ledger and join-back.

This package produces per-fix covariate Parquet tables from Google Earth Engine
batch exports (``prompts/gee_export.md``). It is standalone: nothing under
``movement.data``, ``movement.models``, ``movement.training`` or
``movement.evaluation`` is touched, and no model code imports it.
"""

from .dedup import (
    DedupResult,
    GridSnapper,
    check_reduction,
    dedup_dataset,
    dedup_summary,
    fix_id,
    read_fixes,
    snap_fixes,
    timestamp_iso,
)
from .drive import DriveClient, DriveError, DriveFile, drive_client
from .join import (
    IDENTITY_COLUMNS,
    assert_one_row_per_fix,
    build_fix_table,
    combine_dataset,
    combine_tables,
    drive_fetcher,
    gcs_fetcher,
    load_source_tables,
    local_fetcher,
    output_path,
    prefixed_column,
    wide_csv_path,
    write_wide_csv,
)
from .ledger import (
    LEDGER_COLUMNS,
    STATUSES,
    Chunk,
    build_chunks,
    ledger_path,
    load_ledger,
    record_rows,
    resumable_chunks,
)
from .sources import (
    CADENCES,
    DEFAULT_SOURCES,
    DESTINATIONS,
    OUT_OF_SCOPE_DATASETS,
    Dataset,
    ExportConfig,
    Registry,
    Source,
    age_hours,
    buffer_bands,
    buffer_eligible,
    extract_bits,
    load_registry,
    nominal_time,
    task_selectors,
    time_bucket,
    time_key,
)

__all__ = [
    "CADENCES",
    "DEFAULT_SOURCES",
    "DESTINATIONS",
    "IDENTITY_COLUMNS",
    "LEDGER_COLUMNS",
    "OUT_OF_SCOPE_DATASETS",
    "STATUSES",
    "Chunk",
    "Dataset",
    "DedupResult",
    "DriveClient",
    "DriveError",
    "DriveFile",
    "ExportConfig",
    "GridSnapper",
    "Registry",
    "Source",
    "age_hours",
    "assert_one_row_per_fix",
    "build_chunks",
    "build_fix_table",
    "buffer_bands",
    "buffer_eligible",
    "check_reduction",
    "combine_dataset",
    "combine_tables",
    "dedup_dataset",
    "dedup_summary",
    "drive_client",
    "drive_fetcher",
    "extract_bits",
    "fix_id",
    "gcs_fetcher",
    "ledger_path",
    "load_ledger",
    "load_registry",
    "load_source_tables",
    "local_fetcher",
    "nominal_time",
    "output_path",
    "prefixed_column",
    "read_fixes",
    "record_rows",
    "resumable_chunks",
    "snap_fixes",
    "task_selectors",
    "time_bucket",
    "time_key",
    "timestamp_iso",
    "wide_csv_path",
    "write_wide_csv",
]
